name: CI_LandBOSSE

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: defaults,conda-forge
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pandas numpy scipy xlsxwriter openpyxl openmdao

      - name: Pip Install LandBOSSE
        run: |
          pip install -e . -v

      # Run tests
      - name: Pip Run pytest
        run: |
          pytest landbosse/tests

